# baseurl: /jekyll-test
url: https://albertovargasmoreno.github.io/jekyll-test
# destination: ./docs


# Default settings

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope: 
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values: 
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
